apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
        - name: sender
          image: davyness4dockeries/sender:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:15432/sender_db
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: sender
spec:
  selector:
    app: sender
  ports:
    - port: 8181
      targetPort: 8080
  type: LoadBalancer