spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/oauth2/jwks
  datasource:
    url: jdbc:postgresql://localhost:15431/sender_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/sender
    redis:
      host: localhost
      port: 6379
      password: YXNkZmFzZGY=
  cache:
    type: redis
    cache-names: redis-cache
    redis:
      time-to-live: 30000
  messages:
    basename: i18n/messages
  liquibase:
    change-log: classpath:liquibase/master.xml
  web:
    locale: ru_RU

minio:
  url: http://localhost:9000
  port: 9000
  accessKey: user
  secretKey: password
  secure: false
  bucket: minio-storage
  image-size: 10485760

server:
  port: 8080
  address: localhost

logging:
  level:
    "liquibase": info