version: "3"
services:
  postgres:
    image: postgres:14-alpine3.18
    container_name: sender_db
    environment:
      POSTGRES_DB: "sender_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    volumes:
      - sender-db:/var/lib/postgresql/data
    ports:
      - "15432:5432"

volumes:
  sender-db:
